### ISSUE TITLE
Library crash when the pattern doesn't contain dots

### ISSUE THREAD

**Issue by Frzurita** [osrec/currencyFormatter.js#11]
the error is in the line 1179, the var segment should be declare out of if statement. Otherwise the library crash because it is trying to get the length of undefined

**Comment by osrec** [comment]
Ah, thank you - good spot. We will fix and issue a release shortly :)

Vebby

**Comment by Frzurita** [comment]
thanks! great library by the way 👍

**Comment by osrec** [comment]
Fixed now in latest version (v2.0.0) :)
