### ISSUE TITLE
Convert numbers into USD

### ISSUE THREAD

**Issue by jrock2004** [osrec/currencyFormatter.js#12]
So lets say my locale is `it-it` and I enter in the input `99,99` I want to convert that to `99.99` as the db expects to store this value in `en-us`

**Comment by osrec** [comment]
Please use the `OSREC.CurrencyFormatter.parse` function, added in the latest version (v2.0.0). Eg:

`
OSREC.CurrencyFormatter.parse('€ 100,99', { locale: 'it' }); // Returns 100.99
OSREC.CurrencyFormatter.parse('€ -99,50', { locale: 'it' }); // Returns -99.5
OSREC.CurrencyFormatter.parse('$ 11/25', { decimal: '/' }); // Returns 11.25
`
