### ISSUE TITLE
Missing ES6 feature transpile 

### ISSUE THREAD

**Issue by cat2608** [osrec/currencyFormatter.js#16]
Hi, thanks for the library :)

I would like to know if you could transpile it to ES5. I'm getting an error because of this line:

https://github.com/osrec/currencyFormatter.js/blob/f85b991a03c01f6d66634044a321e57bc3180d22/currencyFormatter.js#L1262

That happens when I run webpack -p so UglifyJS breaks

I've added some changes to be able to use ES6 in this PR #15 in the future. Thanks :)

**Comment by osrec** [comment]
Added in version 2.1.0 - thanks very much for the pull request :)
