### ISSUE TITLE
ReactJS support

### ISSUE THREAD

**Issue by obliviga** [osrec/currencyFormatter.js#17]
Is there anyway to import this utlity in React? Like so:

`import OSREC from 'currencyformatter.js';`

**Comment by Zaifor** [comment]
Yes, you can. 
```JavaScript
import CurrencyFormatter from 'currencyFormatter.js';

CurrencyFormatter.format(volume, { currency: ..., locale: ... });
```

**Comment by osrec** [comment]
Thanks @Zaifor :) 

Marking this as closed @obliviga, please re-open if you still have issues.
