### ISSUE TITLE
Should Allow to specify text colour dynamic if negative value

### ISSUE THREAD

**Issue by balkrishna0007** [osrec/currencyFormatter.js#18]
Should Allow to specify text colour dynamic if negative value

**Comment by balkrishna0007** [comment]
is this incorporated???

**Comment by osrec** [comment]
Hi, we will aim to incorporate into the next release :)

**Comment by osrec** [comment]
Please see the postFormatFunction option available in version 2.1.0 (see docs https://osrec.github.io/currencyFormatter.js/ for more info). This will allow you to achieve what you require :)
