### ISSUE TITLE
Can't disable symbol

### ISSUE THREAD

**Issue by borys-p** [osrec/currencyFormatter.js#22]
Documentation states that I can pass custom symbol to the formatter, but it ignores an empty value.

I need to format only the number, without currency symbol. Currently it's impossible without extra code that strips non-numeric values from output.

**Comment by osrec** [comment]
You have a couple of options:

1) Use a zero-width space: 
`OSREC.CurrencyFormatter.format(1234,` {symbol: '&#8203;'})

2) Specify a pattern without a currency symbol (i.e. no exclamation mark): 
`OSREC.CurrencyFormatter.format(1234,` {pattern: '#,###.00'})

**Comment by borys-p** [comment]
Thanks, I'll try the second option.
Still, the documentation should include that.
