### ISSUE TITLE
Venezuelan Bolivar re-denomination

### ISSUE THREAD

**Issue by ienev** [osrec/currencyFormatter.js#25]
The Central Bank of Venezuela is carrying out a re-denomination of their local currency, with the entry into circulation of the `BOLIVAR SOBERANO`, effective June 4 2018.

The alphabetic code needs to be updated from `VEF` to `VES`.

More details: https://www.currency-iso.org/dam/downloads/dl_currency_iso_amendment_166.pdf

**Comment by ienev** [comment]
It seems the re-denomination has been postponed, for now only unofficial sources mention it:
http://www.xinhuanet.com/english/2018-05/30/c_137217169.htm
https://www.nasdaq.com/article/inflationstricken-venezuela-postpones-currency-overhaul-20180529-01138

**Comment by osrec** [comment]
Ah ok, are we okay to close the issue for now and reopen later if needed?

**Comment by ienev** [comment]
@osrec I guess so. I'll close it.

**Comment by fitojb** [comment]
The redenomination is now in effect
