### ISSUE TITLE
Parsing force toFixed 2 decimals

### ISSUE THREAD

**Issue by cdiaz** [osrec/currencyFormatter.js#28]
For this case:
```javascript
OSREC.CurrencyFormatter.parse('€ -99,50', { locale: 'it' });
```
The current behavior return:
`-99.5`
The expected behavior is:
`Returns -99.50`

Is there any way to do it?

**Comment by osrec** [comment]
Remember, the value returned is a numeric type, not a string. Therefore, you should use val.toFixed(2) on the returned value.
