### ISSUE TITLE
The latest version in npm 

### ISSUE THREAD

**Issue by nolsherry** [osrec/currencyFormatter.js#3]
Hello @osrec ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs/) project.
We want to host this library.
However, we found the latest version in [npm](https://www.npmjs.com/package/currencyformatter.js) is `v1.0.2`, and the latest version in [github](https://github.com/osrec/currencyFormatter.js) is `v1.0.4`.
Could you update the latest version in npm?
Thanks!

cdnjs/cdnjs#9371

**Comment by osrec** [comment]
Hi @nolsherry, 

I will update tomorrow and confirm once it's done :)

Thanks!

**Comment by nolsherry** [comment]
@osrec , thanks for your help!

**Comment by osrec** [comment]
Updated to version 1.04 in npm :)
