### ISSUE TITLE
Prevent number ticking from displaying on the dom

### ISSUE THREAD

**Issue by mlg87** [osrec/currencyFormatter.js#31]
not exactly the best issue title, but im not quite sure what to call this. i would like to prevent the numbers from scrolling/tallying/iterating (whatever one calls this) on the dom like they are doing in [this gif](https://www.dropbox.com/s/01d2chgd415xeq0/number-tick-currencyformatterjs.gif?dl=0). given that this isnt an `async` func, how could i do this?

**Comment by osrec** [comment]
Hi there, this doesn't seem to be a currencyFormatter.js issue. It looks like your charting library is updating the numbers as part of its animation (as your charts animate, the vertical axis is being scaled). To get round it, either turn off animations, or only update the axis formatting at the end of the animation.

**Comment by mlg87** [comment]
@osrec you are correct. thanks for the quick feedback. chart library is [bizcharts](https://github.com/alibaba/BizCharts) btw
