### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by checkonetwo** [osrec/currencyFormatter.js#4]
It will be cool if i could choose currencies what i need

**Comment by osrec** [comment]
I believe you can do this already. Please take a look at the docs (https://osrec.github.io/currencyFormatter.js/). If it answers your questions, please close this issue. Thanks!

**Comment by osrec** [comment]
Closing for now, as I believe the library covers the OPs requirements.

**Comment by Grawl** [comment]
I think @checkonetwo means that ill be good to split a library into core and libraries.
