### ISSUE TITLE
It seems that some versions in npm missed

### ISSUE THREAD

**Issue by nolsherry** [osrec/currencyFormatter.js#5]
Thanks for your help in #3.
Could you help update some versions that we can not find from npm(`1.0.0`  `1.0.1`   `1.0.3`)?
Thanks!

cdnjs/cdnjs#9371

**Comment by osrec** [comment]
Hello - I can try and update, but have never tried to publish an older version to npm. Do you know the command for doing this? Is it as simple as updating package.json and then using npm publish?

**Comment by osrec** [comment]
Actually, I figured it out - all versions are now on npm :)
