### ISSUE TITLE
Consider using unicode currency symbols

### ISSUE THREAD

**Issue by richardvenneman** [osrec/currencyFormatter.js#6]
Hi,

Thanks for the great lib.

What's the reason HTML entities are being used for currency symbols? When rendering the CurrencyFormatter output in React/JSX this requires [dangerouslySetInnerHTML](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml), which is troublesome. Would you consider replacing the HTML entities with unicode characters? If so, I can make a pull request.

**Comment by osrec** [comment]
Hi Richard, yes absolutely :)

**Comment by osrec** [comment]
Thanks for the pull request Richard - this has been merged :)

**Comment by richardvenneman** [comment]
No problem, thanks for the fast merge!

It would be super nice if you could also bump and release a new version on NPM :)

**Comment by osrec** [comment]
Yes absolutely! We'll be adding a few more bug fixes in a couple of weeks and will release all together :)
